---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: 'latest'

inputs:
- name: source
- name: version

outputs:
- name: dist

params:
  GCE_METADATA_HOST: 169.254.169.254

caches:
- path: .gradle/

run:
  path: source/pipeline/scripts/build.sh
