---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: 'latest'

inputs:
- name: source
- name: version

outputs:
- name: dist

run:
  path: source/event-aggregator/pipeline/scripts/build.sh
