apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-service
  annotations:
    sidecar.jaegertracing.io/inject: jaeger
spec:
  template:
    metadata:
      name: event-service
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: event-service
        image: app:0
        env:
        - name: SENTRY_RELEASE
          value: event-service-$(VERSION)
        ports:
        - name: http
          containerPort: 8080
        envFrom:
        - secretRef:
            name: event-service
